# Generated by Django 3.2.8 on 2021-10-25 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_id', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('channel_id', models.CharField(max_length=100)),
                ('channel_name', models.CharField(max_length=100)),
                ('thumbnail_url', models.URLField(max_length=250)),
                ('duration', models.IntegerField()),
                ('published', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField()),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('videos', models.ManyToManyField(related_name='playlists', to='api.Video')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='CurrentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_video_id', models.CharField(default='', max_length=100)),
                ('next_video_id', models.CharField(default='', max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_data', to='api.playlist')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_data', to='api.video')),
            ],
        ),
    ]
