# Generated by Django 3.2.8 on 2021-11-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='country_code',
            field=models.CharField(default='PL', max_length=2),
            preserve_default=False,
        ),
    ]
