# Generated by Django 3.2.8 on 2021-11-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_playlist_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='country_code',
        ),
        migrations.AddField(
            model_name='playlist',
            name='region_code',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
