# Generated by Django 3.2.8 on 2021-12-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211112_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
    ]
