# Generated by Django 3.2.8 on 2021-12-15 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211215_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentdata',
            name='next_video_id',
        ),
        migrations.RemoveField(
            model_name='currentdata',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='currentdata',
            name='previous_video_id',
        ),
        migrations.AddField(
            model_name='currentdata',
            name='next_video',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='next', to='api.video'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentdata',
            name='previous_video',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='api.video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currentdata',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playing', to='api.video'),
        ),
    ]
