# Generated by Django 3.2.8 on 2021-12-15 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211215_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentdata',
            name='next_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='api.video'),
        ),
        migrations.AlterField(
            model_name='currentdata',
            name='previous_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='api.video'),
        ),
    ]
