# Generated by Django 3.2.8 on 2021-12-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211215_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rating', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
