# Generated by Django 3.2.8 on 2021-12-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
