# Generated by Django 3.2.8 on 2021-12-22 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_hint_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hint',
            options={'ordering': ['-rating']},
        ),
    ]
